<a href="https://colab.research.google.com/github/Ashliz1/NYC-Crime-Data---Group-10-/blob/main/term_project_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Crime Analysis: Identifying the Safest County in New York

### Author: (Group 10) Ashley Gomez, Sung Ik Park, Haseulrin Kim
### Date : December 8th, 2025

## Executive Summary

In this project, we analyzed crime patterns across New York State using the SpotCrime dataset to identify which areas appear to be the safest based on reported total crime incidents. Using Python, we cleaned the dataset, created new time-based features, and generated visualizations to explore trends in crime type, geographic distribution, and time-of-day patterns. We conducted both county-level and city-level analyses to compare how crime varies between rural regions and densely populated urban areas, including New York City boroughs. The results showed that crime is heavily concentrated in high-population counties, while rural counties report far fewer incidents as seen in our plots and summaries. Our time-of-day analysis indicated that crime activity is lowest around 9 AM, showing clear variation across different hours of the day. Based on the total incident counts in the data, Seneca County had the fewest reported crimes and was shown to be the safest county in New York. Overall, this analysis provides a descriptive overview of how crime varies across locations and time within the state.

## Table of Contents

1. Introduction
2. Problem Statement / Research Question
3. Data Description
4. Setup and Environment
5. Data Loading
6. Data Preparation
7. Model Planning
8. Model Building / Analysis
9. Limitation
10. Discussion & Interpretation
11. Conclusion
12. References
13. Appendix

## Introduction

Crime patterns can vary widely across New York, especially between urban regions and rural areas. Using the SpotCrime dataset, we can identify where incidents occur most frequently and which areas experience lower crime levels. In this analysis, we focus on factors such as location, crime type, and time of day. We clean the dataset, create new time-based features, and generate visualizations using Python to explore trends. The goal is to gain insights into how crime is distributed across the state and to compare differences between counties and major cities. By examining these spatial and temporal patterns, this analysis provides a foundation for determining which areas are safer based on reported incidents.

## Problem Statement / Research Question

*1. Which area in New York is the safest based on reported crime incidents?*

*2. At what time of day are crime incidents least likely to occur across the state?*

To address this question, we analyze crime distributions across counties and cities, examine which crime types occur most frequently, and explore whether certain hours show higher activity. Understanding these patterns helps highlight where crime clusters occur and where it appears less common. It is expected that more populated regions will have higher incident counts, but the analysis will confirm whether the data support this assumption.

## Data Description

The dataset used in this project contains crime incident reports from locations across New York State. Each entry includes information such as the crime type, timestamp, county, city, ZIP code, address, and geographic coordinates. Before analyzing the data, we needed to convert the timestamp to a datetime format, and we created an additional “hour” variable to support time-of-day analysis. The dataset required basic cleaning to address missing or inconsistent values. Within the data, we primarily focus on location, crime type, and time of day to provide a meaningful insight into overall crime patterns across New York.

## Setup and Environment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Data Loading

In [2]:
# Loading the data set into the data frame.
data_url = "https://raw.githubusercontent.com/Ashliz1/NYC-Crime-Data---Group-10-/refs/heads/main/spotcrime.crime.ny.csv"
df = pd.read_csv(data_url)
df.head()

,_id,CrimeID,StateAbbreviated,State,CountyFips,CountyName,Latitude,Longitude,City,Zip,CBSACode,DMANameCBSA,CBSAStatus,CBSADivision,CBSADivisionTitle,TimeZone,CrimeType,CrimeAddress,CrimeTime
0,67deff0c92344d4401ae7df4,54aa76a5-415d-4c2c-a801-483fe9c4e267,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,94-*** 64TH RD,2025-03-17T01:00:00.000Z
1,67deff0c92344d4401ae7df5,5a9770f1-ae80-400a-8051-6ff765f14f2a,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,55-*** REAR 98TH PL,2025-03-16T23:00:00.000Z
2,67deff0c92344d4401ae7df6,2f104b66-df24-4cbb-b95f-b8ea82537bb5,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Assault,102-*** 42ND AVE,2025-03-16T20:00:00.000Z
3,67deff0d92344d4401ae7df7,cb4c504b-4998-48c3-9ca9-a158061d7375,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,43-*** 108TH ST,2025-03-16T20:00:00.000Z
4,67deff0d92344d4401ae7df8,cd848914-6c49-45b0-aec4-2cb474b128ac,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,94-*** 59TH AVE,2025-03-16T20:00:00.000Z

In [3]:
df.shape

(61824, 19)

In [4]:
df[['City','CountyName','CrimeType','CrimeTime']].head()

     City CountyName CrimeType                 CrimeTime
0  Corona     Queens     Theft  2025-03-17T01:00:00.000Z
1  Corona     Queens     Theft  2025-03-16T23:00:00.000Z
2  Corona     Queens   Assault  2025-03-16T20:00:00.000Z
3  Corona     Queens     Theft  2025-03-16T20:00:00.000Z
4  Corona     Queens     Theft  2025-03-16T20:00:00.000Z

In [5]:
df[["City","CountyName","CrimeType","CrimeTime","Latitude","Longitude"]].head()

     City CountyName CrimeType                 CrimeTime  Latitude  Longitude
0  Corona     Queens     Theft  2025-03-17T01:00:00.000Z   40.7468   -73.8605
1  Corona     Queens     Theft  2025-03-16T23:00:00.000Z   40.7468   -73.8605
2  Corona     Queens   Assault  2025-03-16T20:00:00.000Z   40.7468   -73.8605
3  Corona     Queens     Theft  2025-03-16T20:00:00.000Z   40.7468   -73.8605
4  Corona     Queens     Theft  2025-03-16T20:00:00.000Z   40.7468   -73.8605

## Data Preparation

In [6]:
# Convert CrimeTime to datetime format
df["CrimeTime"] = pd.to_datetime(df["CrimeTime"])

# Drop rows where key fields are missing
df = df.dropna(subset = ["City","CountyName","CrimeType","CrimeTime"])

#Extract hour of the day from the timestamp
df["hour"] = df["CrimeTime"].dt.hour

df.head()

,_id,CrimeID,StateAbbreviated,State,CountyFips,CountyName,Latitude,Longitude,City,Zip,CBSACode,DMANameCBSA,CBSAStatus,CBSADivision,CBSADivisionTitle,TimeZone,CrimeType,CrimeAddress,CrimeTime,hour
0,67deff0c92344d4401ae7df4,54aa76a5-415d-4c2c-a801-483fe9c4e267,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,94-*** 64TH RD,2025-03-17 01:00:00+00:00,1
1,67deff0c92344d4401ae7df5,5a9770f1-ae80-400a-8051-6ff765f14f2a,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,55-*** REAR 98TH PL,2025-03-16 23:00:00+00:00,23
2,67deff0c92344d4401ae7df6,2f104b66-df24-4cbb-b95f-b8ea82537bb5,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Assault,102-*** 42ND AVE,2025-03-16 20:00:00+00:00,20
3,67deff0d92344d4401ae7df7,cb4c504b-4998-48c3-9ca9-a158061d7375,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,43-*** 108TH ST,2025-03-16 20:00:00+00:00,20
4,67deff0d92344d4401ae7df8,cd848914-6c49-45b0-aec4-2cb474b128ac,NY,New York,36081,Queens,40.7468,-73.8605,Corona,11368,35620.0,"New York-Newark-Jersey City, NY-NJ-PA",Metropolitan Statistical Area,35614.0,"New York-Jersey City-White Plains, NY-NJ",EST,Theft,94-*** 59TH AVE,2025-03-16 20:00:00+00:00,20

### Functions

In [7]:
def analyze_top_crime_type_and_peak_crime_hours_nyc(df):
  #Filter data to NYC only

  df_nyc = df[df["City"]=="New York"]

  # Top 10 crime types
  top_crime_types = df_nyc["CrimeType"].value_counts().head(10)
  # Top 10 hours of the day with the highest number of crime incidents
  top_crime_hours = df_nyc["hour"].value_counts().head(10)

  return top_crime_types, top_crime_hours

In [8]:
def analyze_crime_by_city(df):
  # find the top 3 cities with the highest crime counts
  top_cities = df["City"].value_counts().head(10)

  # filter df to only include rows from those top 5 cities to minimize inefficiency
  df_top = df[df["City"].isin(top_cities.index)]

  # 1. group by city + crime type
  # 2. count number of incidents
  # 3. sort counts in descending order to have top city to be on the first
  # 4. reset index to normal columns
  # 5. a) group again by city and keep top 5 rows per city
  # 5. b) group again by city and crime type and keep the top (most frquent) hour
  top_types_per_city = (
      df_top.groupby(["City","CrimeType"])
      .size()
      .reset_index(name="Count")
      .sort_values(["City","Count"], ascending=[True,False])
      .groupby("City")
      .head(3)
  )
  peak_hours = (
      df_top.groupby(["City","CrimeType","hour"])
      .size()
      .reset_index(name="Count")
      .sort_values(["City","CrimeType","Count"], ascending=[True,True,False])
      .groupby(["City","CrimeType"])
      .head(1)
  )

  return top_cities, top_types_per_city, peak_hours

In [9]:
# County level crime function
def analyze_crime_by_county(df):
  top_counties = df["CountyName"].value_counts().head(10)  # Top 10 counties highest crime (least safe)

  lowest_counties = (
      df["CountyName"].value_counts()                      # Top 10 counties by lowest crime (safe)
        .sort_values(ascending=True)
        .head(10)
  )

  df_top = df[df["CountyName"].isin(top_counties.index)] # filter df for the top 10 counties for more data

# Top 3 crimes types in top 10 counties
  top_types_per_county = (
      df_top.groupby(["CountyName","CrimeType"])
      .size()
      .reset_index(name="Count")
      .sort_values(["CountyName","Count"], ascending=[True,False])
      .groupby("CountyName")
      .head(3)
  )
# peak hour for each crime type in top counties
  peak_hours = (
      df_top.groupby(["CountyName","CrimeType","hour"])
      .size()
      .reset_index(name="Count")
      .sort_values(["CountyName","CrimeType","Count"], ascending=[True,True,False])
      .groupby(["CountyName","CrimeType"])
      .head(1)
  )

  return top_counties, lowest_counties, top_types_per_county, peak_hours

## Model Planning

This project uses descriptive analytics to explore crime trends, including grouping incidents by county and city to compare crime levels, examining the distribution of crime types, mapping geographic patterns through scatter and hexbin plots, and identifying peak crime hours. We used Python functions to summarize key statistics, including the highest- and lowest-crime regions, the most common crime types in high-crime areas, and time-of-day patterns. This helped us provide a way to evaluate the dataset and ultimately determine which areas appear safer based on reported incidents.

## Model building / Analysis

In [11]:
top_cities, top_types, peak_hours = analyze_crime_by_city(df)
top_crime_types, top_crime_hours = analyze_top_crime_type_and_peak_crime_hours_nyc(df)

In [ ]:
top_cities

City
New York         6533
Brooklyn         2026
Buffalo          1761
Rochester        1759
Syracuse         1196
Bronx            1033
Albany            693
Staten Island     669
Jamaica           606
Schenectady       408
Name: count, dtype: int64

In [ ]:
top_types

             City CrimeType  Count
0          Albany    Arrest    308
1          Albany   Assault    199
5          Albany  Shooting    135
13          Bronx     Theft    480
8           Bronx   Assault    339
11          Bronx   Robbery     60
21       Brooklyn     Theft   1155
16       Brooklyn   Assault    585
19       Brooklyn   Robbery    118
30        Buffalo     Theft    970
25        Buffalo   Assault    313
27        Buffalo     Other    220
36        Jamaica     Theft    355
32        Jamaica   Assault    183
33        Jamaica  Burglary     42
45       New York     Theft   3539
40       New York   Assault   1750
42       New York     Other    371
53      Rochester     Theft   1206
50      Rochester     Other    158
48      Rochester   Assault    139
58    Schenectady     Other    314
57    Schenectady  Burglary     39
55    Schenectady    Arrest     16
69  Staten Island     Theft    400
64  Staten Island   Assault    206
65  Staten Island  Burglary     27
74       Syracuse     Other    537
77       Syracuse     Theft    239
72       Syracuse   Assault    217

In [ ]:
peak_hours

          City  CrimeType  hour  Count
4       Albany     Arrest     5     85
21      Albany    Assault     5     63
30      Albany   Burglary     3      7
34      Albany      Other    14     30
36      Albany    Robbery     6      5
...        ...        ...   ...    ...
1098  Syracuse      Other    18     46
1104  Syracuse    Robbery     3      5
1111  Syracuse   Shooting     3      2
1128  Syracuse      Theft    17     34
1145  Syracuse  Vandalism    17      8

[79 rows x 4 columns]

County-level Crime Analysis

In [ ]:
# county crimes reported per county
county_counts = df["CountyName"].value_counts()
county_counts

In [ ]:
# Top 10 counties with highest crime reported.
top10_counties = county_counts.head(10)
top10_counties

In [ ]:
plt.figure(figsize=(10,6))
top10_counties.plot(kind="bar")

plt.title("New York State: Top 10 Counties with the Highest Number of Crimes")
plt.xlabel("County")
plt.ylabel("Number of Crimes")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# The bar graph shown below represents the least safest regions in New York State
# based on the top 10 highest number of crimes being reported.
# New York reports significantly more incidents, suggesting it is the least safe county,
# which could be due to population density, tourism, urban activities etc.

In [ ]:
# top 10 counties with the lowest crime counts reported.
bottom10_counties = county_counts.tail(10)
bottom10_counties

In [ ]:
# Bar chart for bottom 10
plt.figure(figsize=(10,6))
bottom10_counties.plot(kind="bar")

plt.title("New York State: Top 10 Counties with the Lowest Number of Crimes")
plt.xlabel("County")
plt.ylabel("Number of Crimes")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# The bar graph shown below represents the safest regions in New York State
# based on the top 10 lowest numbers of crime being reported. Seneca reports the lowest crime rate,
# suggesting it is the safest place in New York State. This could be due to the county having a smaller population, rural characteristics etc.

In [ ]:
# Crime type distribution by county - creating a pivot tabel
county_crime_pivot = pd.pivot_table(df,
                                    index="CountyName",    # each row will be county
                                    columns="CrimeType",   # each column will be type of crimes
                                    values="CrimeID",      # counting number of incidents reported
                                    aggfunc="count",
                                    fill_value=0)
county_crime_pivot.head()

In [ ]:
from numpy._core.defchararray import count
# creating Heatmap - to show crime type distribution across counties
# dark red = most amount of crime reported
# lighter red shades = least amount of crime reported

plt.figure(figsize=(12,10))
sns.heatmap(county_crime_pivot, cmap="Reds", linewidths=0.5)
plt.title("Crime Type Distribution by County in New York State")
plt.xlabel("Crime Type")
plt.ylabel("County")
plt.tight_layout()
plt.show()

# The heat map show how different crime types vary across counties in NY state. The darker shades of red indicate
# higher number of incident, making it easy to see which counties experience more of certian crimes. For example,
# it shows New York county has a noticeably higher levels of theft compared to other counties.

In [ ]:
# Geographic crime density across New York State (scatter plot)

plt.figure(figsize=(10,6))

plt.scatter(df["Longitude"],
            df["Latitude"],
            alpha=0.5,
            s=10,
            color = "red")
plt.title("Geographic Crime Distribution Across New York State")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.tight_layout()
plt.show()

# Using a scatter plot it shows exact locations of every report crime using longitude and latitude.
# This shows an accurate visualization of identifying where incidents occurred. Revealing the natural
# clusters of crime across New York State and highlights how incidents are heavily concentrated
# around major cities and densely populated regions.

In [ ]:
# Geographic crime density across New York State
# Darker red = higher crime density
# lighter = lowest amount of crime density

plt.figure(figsize=(10,6))

plt.hexbin(df["Longitude"],
           df["Latitude"],
           gridsize=50,
           cmap="Reds",
           mincnt=1)
plt.colorbar(label= "Number of Crime")
plt.title("Geographic Crime Density Across New York State (Hexbin Map)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.tight_layout()
plt.show()

# We used a hexbin plot to show the density of crime incidents across New York State.
# Unlike the scatter plot, which shows every individual point, the hexbin plot groups
# nearby incidents into hexagonal bins. This helps us see where crime is most concentrated
# when there are too many overlapping points to interpret clearly. The purpose of this plot
# is to provide a clearer view of high-density crime areas while still using the underlying
# geographic coordinates.

In [ ]:
# Crime Frequency by Hour of Day (Statewide)
# counts crime reported for each housr of the day across New York State.
hour_counts = df["hour"].value_counts().sort_index()
hour_counts

In [ ]:
# Crime occurrence by hour of the day.
# Using Bar chart to show what time of day the most crime happens

plt.figure(figsize=(10,6))
hour_counts.plot(kind="bar")

plt.title("Crime Frequency by Hour of Day (Statewide)")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Crimes")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# This bar graph shows the distribution of reported crime incidents throughout the 24 hr day.
# Peaks during particular hours are real when crime incidents are more likely to occur,
# this suggests hour 5 is the peak of crime statewide.

In [ ]:
top_counties, lowest_counties, top_types_county, peak_hours_county = analyze_crime_by_county(df)

In [ ]:
top_counties

In [ ]:
lowest_counties

In [ ]:
top_types_county

In [ ]:
peak_hours_county

In [ ]:
# Safest county identification
safest_county = lowest_counties.index[0]
safest_count = lowest_counties.iloc[0]

print("Safest County in New York State:", safest_county)
print("Total number of reported crimes:", safest_count)

# Based on the function results, the county with the fewest total crime incidents is Seneca,
# which is identified as the safest county in New York.

In [ ]:
top_crime_types_nyc, top_crime_hours_nyc = analyze_top_crime_type_and_peak_crime_hours_nyc(df)

In [ ]:
plt.figure(figsize=(10,6))
top_crime_types_nyc.plot(kind="bar")

plt.title("The Most Frequent Crime Types in New York City")
plt.xlabel("Crime Types")
plt.ylabel("Number of Crimes")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# The bar chart shows that theft is the most frequently reported crime in NYC,
# followed by assault, while all other crime types appear at much lower levels.

In [ ]:
plt.figure(figsize=(10,6))
top_crime_hours_nyc.plot(kind="bar")

plt.title("Hours with Highest Crime Frequency in New York City")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Crimes")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# # This bar chart shows the hours of the day with the highest crime frequency in New York City.
# The late evening hours—especially around 21:00 (9 PM), 2:00 AM, and 18:00 (6 PM)—have the most
# reported incidents. This suggests that crime is more common during busy evening periods and
# late-night activity.

ZIP Code Analysis Attempt

We attempted to analyze crime counts by ZIP code to identify the safest ZIP-level areas.  
However, the output showed that nearly every ZIP code has the same number of incidents (approximately 50 each).  
This indicates that the dataset may have been uniformly sampled by ZIP code rather than representing real-world crime volume.

Because of this pattern, ZIP-level comparisons are not meaningful and cannot be used to determine which ZIP codes are safer.

In [ ]:
# Attempt to analyze crime counts by ZIP code
zip_counts = df["Zip"].value_counts()
zip_counts.head(20)

Zip
14902    50
11368    50
11385    50
11208    50
10467    50
14653    50
14652    50
14651    50
14650    50
14649    50
14647    50
14646    50
14644    50
14643    50
14642    50
14639    50
14638    50
14603    50
11218    50
11375    50
Name: count, dtype: int64

## Limitations

While this analysis provides useful insights into crime patterns across New York State, there are a few clear limitations to acknowledge.

1. ZIP-code–level analysis was not possible.

    When we examined crime counts by ZIP code, nearly every ZIP appeared with the same number of incidents (around 50 each).

    This suggests that the dataset was uniformly sampled across ZIP codes rather than reflecting the actual distribution of crime.Because of this, ZIP-level comparisons are not meaningful.

2. The time-of-day analysis cannot explain the underlying cause of the patterns.

    Although the data clearly show that crime is highest around 5 AM and lowest around 9 AM, the dataset does not include any contextual factors—such as population activity, environment, or police presence—that could explain why these patterns appear. Therefore, we can describe when crime is more or less frequent, but we cannot determine why these differences occur.


Considering these limitations, the results of this project should be viewed as a descriptive analysis of spatial and temporal crime patterns rather than an explanation of the causes behind them.

## Discussion and Results

The data we analyzed examined crime across New York State to determine which areas are the least and most safe. The analysis shows a clear divide between highly populated urban regions and rural counties. New York County reported the highest number of crime incidents, while counties with smaller populations reported significantly fewer. The heat map further showed that crime types such as theft and assault are concentrated in these densely populated counties.

City-level analysis supports this pattern. Boroughs like Manhattan, Brooklyn, and the Bronx appear most frequently in the highest-crime categories, mirroring trends at the county level. This consistency across both city and county data strengthens the reliability of our overall findings. Geographic visualizations revealed strong spatial clustering, with crime incidents concentrated near major urban centers, while rural regions showed minimal activity.

Time-of-day analysis also indicated that crime peaks around 5 AM, suggesting early morning vulnerability, while 9 AM had the fewest reported incidents, making it the safest hour of the day according to this data.

Our summary of county-level totals confirmed the safest counties with Seneca County in New York recording the lowest number of reported crimes. This aligns with the broader trend that rural counties generally experience less crime.

Overall, these results provide clear spatial and temporal patterns of crime across New York State and help highlight both the safest locations and the safest times of day based on reported incidents.

## Conclusion

This project explored crime patterns across New York State to determine which area is the safest. Through county-level and city-level analysis, we found consistent evidence that crime is heavily concentrated in densely populated regions such as New York County and the New York City boroughs. Visualizations of crime type distributions and geographic clusters reinforced these spatial patterns, while rural counties reported substantially fewer incidents.

Time-of-day analysis further showed that crime activity peaks around 5 AM and is lowest around 9 AM, identifying late morning as the safest period of the day. Based on total crime counts and function results, Seneca County was identified as the safest county in New York. Overall, these findings demonstrate how population density, urban development, and geographic location influence crime distribution across the state.

## References



1. Pandas Development Team. Pandas Documentation: DataFrame GroupBy Reference. pandas.pydata.org, https://pandas.pydata.org/docs/reference/groupby.html.
2. Pandas Development Team. Series.value_counts Documentation. pandas.pydata.org, https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html.
3. Waskom, Michael et al. Seaborn Heatmap Function Documentation. seaborn.pydata.org, https://seaborn.pydata.org/generated/seaborn.heatmap.html.
4. Hunter, J. D. et al. Matplotlib Bar Chart Examples. matplotlib.org, https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_label_demo.html.
5.  Deep Dive Data Science. "Heatmap Tutorial in Python." YouTube, https://youtu.be/1lAxBhGAu5k?si=o2JstcEFi9uOjswD.
6. Data with Python. "Hexbin Plot Tutorial." YouTube, https://youtu.be/G1Sfetii7kU?si=rhN1aHuNzPcJybXD.
7. NYC Crime Dataset. Provided by CIS9650 Instructor for Term Project, 2025.

## Appendix

This section containts supplementary information that supports the main analysis.

In [ ]:
# Dataset Columns
df.columns

In [ ]:
# Missing Value Summary
df.isna().sum()

In [ ]:
# Random Sample Records from the Dataset
df.sample(10)